
spring:
    profiles: uat-alpha

server:
  port: 9300

eureka:
  instance:
    hostname: 192.168.56.204
    metadataMap:
      zone: alpha
    statusPageUrl: http://${eureka.instance.hostname}:${server.port}/info
    healthCheckUrl: http://${eureka.instance.hostname}:${server.port}/health

  client:
    serviceUrl:
      defaultZone: http://192.168.56.202:8761/eureka/
    healthcheck:
      enabled: true

---

spring:
    profiles: uat-omega

server:
  port: 9300

eureka:
  instance:
    hostname: 192.168.56.205
    metadataMap:
      zone: omega
    statusPageUrl: http://${eureka.instance.hostname}:${server.port}/info
    healthCheckUrl: http://${eureka.instance.hostname}:${server.port}/health

  client:
    serviceUrl:
      defaultZone: http://192.168.56.203:8761/eureka/
    healthcheck:
      enabled: true

---

spring:
    profiles: pre-prod-alpha

server:
  port: 9300
  ssl:
    key-store: classpath:192.168.56.204.jks
    key-store-password: changeit
    trust-store: classpath:ms-truststore.jks
    trust-store-password: changeit

eureka:
  instance:
    hostname: 192.168.56.204
    metadataMap:
      zone: alpha
    securePortEnabled: true
    nonSecurePortEnabled: false
    securePort: ${server.port}
    statusPageUrl: https://${eureka.instance.hostname}:${server.port}/info
    healthCheckUrl: https://${eureka.instance.hostname}:${server.port}/health

  client:
    serviceUrl:
      defaultZone: https://192.168.56.202:8761/eureka/
    healthcheck:
      enabled: true

---

spring:
    profiles: pre-prod-omega

server:
  port: 9300
  ssl:
    enabled: true
    key-store: classpath:192.168.56.205.jks
    key-store-password: changeit
    trust-store: classpath:ms-truststore.jks
    trust-store-password: changeit

eureka:
  instance:
    hostname: 192.168.56.205
    metadataMap:
      zone: omega
    securePortEnabled: true
    nonSecurePortEnabled: false
    securePort: ${server.port}
    statusPageUrl: https://${eureka.instance.hostname}:${server.port}/info
    healthCheckUrl: https://${eureka.instance.hostname}:${server.port}/health

  client:
    serviceUrl:
      defaultZone: https://192.168.56.203:8761/eureka/
    healthcheck:
      enabled: true

---

spring:
  application:
    name: customer-service